In [3]:
import torch
print(torch.__version__)

2.5.1+cu121


In [4]:
torch.cuda.is_available()

True

In [5]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

6

In [8]:
vector = torch.tensor([4,5])
vector

tensor([4, 5])

In [9]:
vector.ndim

1

In [11]:
vector.item()

RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

In [12]:
vector.shape

torch.Size([2])

In [13]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([2, 3])

In [20]:
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9],
                       [10,11,12]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [21]:
tensor.ndim

3

In [22]:
tensor.shape

torch.Size([1, 4, 3])

In [25]:
tensor1 = torch.tensor(tensor)
tensor1

C:\Users\LEGION\AppData\Local\Temp\ipykernel_18356\1205148242.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor1 = torch.tensor(tensor)


tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])