In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.5.1+cu121
True


In [5]:
one = torch.ones(2,3)
one, one.dtype, one.device

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32,
 device(type='cpu'))

In [6]:
one = torch.ones((3,2), dtype=torch.int32, device='cuda', requires_grad=False)
one, one.dtype, one.device

(tensor([[1, 1],
         [1, 1],
         [1, 1]], device='cuda:0', dtype=torch.int32),
 torch.int32,
 device(type='cuda', index=0))

In [10]:
zero = torch.zeros(3,2)
zero, zero.dtype, zero.device, zero.requires_grad

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]),
 torch.float32,
 device(type='cpu'),
 False)

In [12]:
zero = torch.zeros((3,2), dtype=torch.int32, device='cuda', requires_grad=True)
zero, zero.dtype, zero.device

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [13]:
zero = torch.zeros((3,2), dtype=torch.float32, device='cuda', requires_grad=True)
zero, zero.dtype, zero.device

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.]], device='cuda:0', requires_grad=True),
 torch.float32,
 device(type='cuda', index=0))

In [57]:
empty = torch.empty(2,2)
empty

tensor([[2.0934e+34, 1.1925e-42],
        [0.0000e+00, 0.0000e+00]])

In [45]:
empty.fill_(1.)

tensor([[1., 1.],
        [1., 1.]])

In [145]:
torch.empty((3,3), dtype=torch.float32, device='cpu', requires_grad=True)

tensor([[2.1111e+34, 1.1925e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]], requires_grad=True)