In [1]:
import torch

In [2]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [33]:
b = torch.Tensor(2,3)
b

tensor([[1.6273e-19, 1.9983e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [27]:
torch.tensor(3)

tensor(3)

In [30]:
torch.Tensor(3)

tensor([1.6348e-19, 1.9983e-42, 0.0000e+00])

In [34]:
torch.Tensor([1, 2, 3])

tensor([1., 2., 3.])