In [1]:
import torch

In [3]:
full = torch.full((2,3), 7)
full

tensor([[7, 7, 7],
        [7, 7, 7]])

In [8]:
torch.full(size=(2,3), fill_value=20, dtype=torch.float32, device='cpu', requires_grad=False)

tensor([[20., 20., 20.],
        [20., 20., 20.]])

In [10]:
eye = torch.eye(3,4)
eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [11]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])