In [1]:
import torch

In [2]:
full = torch.full((2,3), 7)
full

tensor([[7, 7, 7],
        [7, 7, 7]])

In [3]:
torch.full(size=(2,3), fill_value=20, dtype=torch.float32, device='cpu', requires_grad=False)

tensor([[20., 20., 20.],
        [20., 20., 20.]])

In [4]:
eye = torch.eye(3,4)
eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [5]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [7]:
torch.eye(n=3, m=5, dtype=torch.float32, device='cpu', requires_grad=False)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [11]:
vector = torch.tensor([10,20,30,40])
torch.diag(vector)

tensor([[10,  0,  0,  0],
        [ 0, 20,  0,  0],
        [ 0,  0, 30,  0],
        [ 0,  0,  0, 40]])

In [12]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
torch.diag(matrix)

tensor([1, 5, 9])

In [17]:
vector = torch.tensor([10,20,30,40])
torch.diag(vector, diagonal=2)

tensor([[ 0,  0, 10,  0,  0,  0],
        [ 0,  0,  0, 20,  0,  0],
        [ 0,  0,  0,  0, 30,  0],
        [ 0,  0,  0,  0,  0, 40],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0]])

In [19]:
vector = torch.tensor([10,20,30,40])
torch.diag(vector, diagonal=-1)

tensor([[ 0,  0,  0,  0,  0],
        [10,  0,  0,  0,  0],
        [ 0, 20,  0,  0,  0],
        [ 0,  0, 30,  0,  0],
        [ 0,  0,  0, 40,  0]])