In [2]:
import torch

In [7]:
integer = torch.randint(low=50, high=100, size=(5,4))
integer

tensor([[63, 82, 68, 84],
        [56, 55, 59, 97],
        [89, 87, 90, 98],
        [65, 81, 50, 78],
        [98, 74, 62, 83]])

In [8]:
torch.rand(2,3)

tensor([[0.6902, 0.7833, 0.2916],
        [0.7425, 0.0316, 0.5511]])

In [9]:
torch.randn(2,3)

tensor([[-1.7968, -1.3809, -0.8323],
        [-2.3116,  1.1552, -0.6781]])