In [1]:
import torch

In [2]:
torch.randperm(10)

tensor([8, 9, 0, 3, 1, 2, 5, 4, 6, 7])

In [3]:
torch.randperm(10)

tensor([6, 5, 8, 7, 2, 9, 4, 0, 1, 3])

In [6]:
data = torch.tensor([100,200,300,400])

In [7]:
data.size()

torch.Size([4])

In [12]:
data[torch.randperm(data.size(0))]

tensor([200, 100, 400, 300])

In [20]:
probs = torch.tensor([0.1,0.3,0.6])
torch.multinomial(probs, num_samples=5, replacement=True)

tensor([2, 1, 2, 1, 2])

In [25]:
probs = torch.tensor([0.1,0.3,0.6])
torch.multinomial(probs, num_samples=3, replacement=False)

tensor([2, 1, 0])

In [26]:
torch.normal(mean=0.5, std=2.5, size=(3,3))

tensor([[ 0.5498,  1.7450, -3.0784],
        [-0.0542,  1.5886, -0.8846],
        [ 0.4203,  2.8050,  4.0808]])

In [27]:
means = torch.tensor([0.0, 1.0, 2.0])
stds = torch.tensor([1.0,1.0,1.0])

torch.normal(mean=means, std=stds)

tensor([1.1818, 2.2626, 2.5348])