In [1]:
import torch

In [3]:
tensor = torch.tensor([[1, 2, 3], [3, 4, 5]])
tensor

tensor([[1, 2, 3],
        [3, 4, 5]])

In [4]:
torch.zeros_like(tensor)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [6]:
torch.ones_like(tensor)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [10]:
torch.empty_like(tensor)

tensor([[6175982621872,             0,             0],
        [            0,             0,             0]])

In [11]:
torch.full_like(tensor, fill_value=10)

tensor([[10, 10, 10],
        [10, 10, 10]])