In [1]:
import torch

In [ ]:
tensor = torch.tensor([[1, 2], [3, 4]])
tensor

tensor([[1, 2],
        [3, 4]])

In [4]:
torch.rand_like(tensor)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [5]:
torch.rand_like(tensor, dtype=torch.float)

tensor([[0.5751, 0.3261],
        [0.4181, 0.9349]])

In [6]:
torch.randn_like(tensor, dtype=torch.float)

tensor([[-0.3154,  0.0627],
        [ 0.0798, -0.8427]])

In [7]:
torch.randint_like(tensor, low=10, high=100)

tensor([[16, 32],
        [22, 15]])