In [1]:
import torch

In [2]:
torch.arange(start=0, end=10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [9]:
torch.linspace(start=0,end=10, steps=5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])