In [3]:
import torch

In [4]:
torch.arange(start=0, end=10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [8]:
torch.linspace(start=0,end=10, steps=5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [9]:
torch.linspace(20,30,5)

tensor([20.0000, 22.5000, 25.0000, 27.5000, 30.0000])

In [13]:
torch.logspace(start=0,end=2,steps=5, base=10)

tensor([  1.0000,   3.1623,  10.0000,  31.6228, 100.0000])

In [14]:
torch.linspace(start=0,end=2, steps=5)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000])

In [15]:
torch.logspace(start=0,end=2,steps=5, base=2)

tensor([1.0000, 1.4142, 2.0000, 2.8284, 4.0000])