In [1]:
import torch

In [2]:
x = torch.tensor([1.0, 2.0,])
x, x.device

(tensor([1., 2.]), device(type='cpu'))

In [4]:
x_gpu = x.to('cuda')
x_gpu, x_gpu.device

(tensor([1., 2.], device='cuda:0'), device(type='cuda', index=0))

In [6]:
x, x.device

(tensor([1., 2.]), device(type='cpu'))

In [7]:
y = x.cuda()
y, y.device

(tensor([1., 2.], device='cuda:0'), device(type='cuda', index=0))

In [8]:
x = y.cpu()
x, x.device

(tensor([1., 2.]), device(type='cpu'))

In [9]:
x = torch.tensor([1.0, 2], device='cpu')
x, x.device

(tensor([1., 2.]), device(type='cpu'))

In [10]:
y = torch.tensor([3.0, 4], device='cuda')
y, y.device

(tensor([3., 4.], device='cuda:0'), device(type='cuda', index=0))

In [13]:
device  = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [15]:
x = x.to(device)
x, x.device

(tensor([1., 2.], device='cuda:0'), device(type='cuda', index=0))